// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = {
    "Python": {
      "Fortran": "throws more exceptions than"
    },
    "Java": {
      "Python": "burns"
    },
    "Fortran": {
      "Java": "confuses",
      "Python": "confuses"
    }
  };

  module.exports = root;

}).call(this);
