// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = {
    "Rock": {
      "Scissors": "crushes",
      "Rock": "smashes"
    },
    "Paper": {
      "Rock": "wraps",
      "Paper": "cuts"
    },
    "Scissors": {
      "Paper": "snips",
      "Scissors": "bends"
    }
  };

  module.exports = root;

}).call(this);
